
Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-7hw4h[0m
{"level":"warn","ts":1581014802.3504174,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581014802.3518417,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-26hzl[0m
{"level":"warn","ts":1581014802.791383,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1581014802.8004289,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-cramte-jx-qs-python-master-rele-bds7t-ffd4j[0m
{"level":"warn","ts":1581014808.0147228,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1581014809.9831789,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/******/**-qs-python.git @ v0.0.6 in path /workspace/source"}

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:b3783baf1717401bd2a77d8e4485a6cdb42f8dee
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
[36mINFO[0m[0001] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0001] Downloading base image python:onbuild        
[36mINFO[0m[0003] Executing 3 build triggers                   
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] Checking for cached layer docker.io/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73... 
[36mINFO[0m[0004] No cached layer found for cmd RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Unpacking rootfs as cmd RUN pip install --no-cache-dir -r requirements.txt requires it. 
[36mINFO[0m[0039] Taking snapshot of full filesystem...        
[36mINFO[0m[0066] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0066] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0066] Taking snapshot of files...                  
[36mINFO[0m[0066] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0066] cmd: /bin/sh                                 
[36mINFO[0m[0066] args: [-c pip install --no-cache-dir -r requirements.txt] 
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[36mINFO[0m[0071] Taking snapshot of full filesystem...        
[36mINFO[0m[0092] Pushing layer docker.io/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73 to cache now 
[36mINFO[0m[0092] Using files from context: [/workspace/source] 
[36mINFO[0m[0092] COPY . /usr/src/app                          
[36mINFO[0m[0092] Taking snapshot of files...                  
[36mINFO[0m[0092] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0092] COPY requirements.txt .                      
[36mINFO[0m[0092] Taking snapshot of files...                  
[36mINFO[0m[0092] ENV PORT 8080                                
[36mINFO[0m[0092] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0092] EXPOSE 8080                                  
[36mINFO[0m[0092] cmd: EXPOSE                                  
[36mINFO[0m[0092] Adding exposed port: 8080/tcp                
[36mINFO[0m[0092] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0092] ENTRYPOINT ["python"]                        
[36mINFO[0m[0092] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0092] CMD ["app.py"]                               
[36mINFO[0m[0092] No files changed in this command, skipping snapshotting. 
[33mWARN[0m[0094] error uploading layer to cache: failed to push to destination index.docker.io/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73: unsupported status code 401; body:  
2020/02/06 18:48:28 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/02/06 18:48:28 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/02/06 18:48:28 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/02/06 18:48:29 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/02/06 18:48:29 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/02/06 18:48:29 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/02/06 18:48:29 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/02/06 18:48:29 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/02/06 18:48:29 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/02/06 18:48:30 pushed blob: sha256:15b53bc1c135420fe8c7d0817ca1e2a81fda6970c4285e60fb8cd12842975ecb
2020/02/06 18:48:30 pushed blob: sha256:408f45fe7285296a06c781eb91a662e901ec18700d1d8f4977a1d3d9f6e6c87f
2020/02/06 18:48:30 pushed blob: sha256:2d5832383786c9f6f69ed5b9f163b72918a0013302ff5b990b0e031bdec5ddf6
2020/02/06 18:48:30 pushed blob: sha256:1210ffd9b1dcccc6ea33d27422494dc851a772cf1e948bc4db9c69ea84fd37a2
2020/02/06 18:48:31 pushed blob: sha256:860b0dd8048065e40e6b529db272d1d67cf8fd3b5b2658f695304d3b8598c049
2020/02/06 18:48:32 index.docker.io/******/**-qs-python:0.0.6: digest: sha256:b285d557b52e058eec2e2147869731904aa84cbd88bd6747d74ae1e99cba64ed size: 2385

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/**-qs-python to an unshallow repository
Generating change log from git ref 6403751766c19428d43200475141b9fdf7141699 => 3ddbd80be52d5beb1362af4f09145b1a85a6b92e
Associating user ****** in users.jenkins.io with email 42623182+******@users.noreply.github.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user ****** in users.jenkins.io
WARNING: Failed to enrich commit 4bfe9acf94cbfb870afd2dd764023cf05fc5effb with issues: User.jenkins.io "******" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
WARNING: Failed to enrich commit 4bfe9acf94cbfb870afd2dd764023cf05fc5effb with issues: users.jenkins.io "x-0" already exists
Finding issues in commit messages using git format
WARNING: No release found for ******/**-qs-python and tag v0.0.6 so creating a new release
Updated the release information at https://github.com/******/**-qs-python/releases/tag/v0.0.6
generated: /workspace/source/charts/**-qs-python/templates/release.yaml
Created Release **-qs-python-0-0-6 resource in namespace **
Updating PipelineActivity ******-**-qs-python-master-6 with version 0.0.6
Updated PipelineActivities ******-**-qs-python-master-6 with release notes URL: https://github.com/******/**-qs-python/releases/tag/v0.0.6

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file **-qs-python-0.0.6.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mcramte-jx-qs-python-master-rele-bds7t-6[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app **-qs-python version 0.0.6 to namespace **-staging
WARNING: 
Created Pull Request: https://github.com/******-org/environment-kind1-staging/pull/3
Added label updatebot to Pull Request https://github.com/******-org/environment-kind1-staging/pull/3
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/3
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/3
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/3
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/3
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/3
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/3
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/3
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/3
Pull Request https://github.com/******-org/environment-kind1-staging/pull/3 is merged at sha 1a955998dadec296f4cceb955fb37c8fee2a7a1c
Pull Request merged but we are not waiting for the update pipeline to complete!
